In [1]:
from StockSeriesAPI import *

In [2]:
IBM_data = TIME_SERIES_DAILY_ADJUSTED('IBM')

In [3]:
csv = TIME_SERIES_TO_CSV(IBM_data)
display(csv)

,open,high,low,close,adjusted close,volume,dividend amount,split coefficient
2021-01-11,127.95,129.675,127.66,128.58,128.58,5602466,0.0000,1.0
2021-01-08,128.57,129.32,126.98,128.53,128.53,4676487,0.0000,1.0
2021-01-07,130.04,130.46,128.26,128.99,128.99,4507382,0.0000,1.0
2021-01-06,126.9,131.88,126.72,129.29,129.29,7956740,0.0000,1.0
2021-01-05,125.01,126.68,124.61,126.14,126.14,6114619,0.0000,1.0
...,...,...,...,...,...,...,...,...
2020-08-25,126.0,126.82,124.49,124.64,122.905933766,2977697,0.0000,1.0
2020-08-24,123.79,126.06,123.36,125.68,123.931464664,4070816,0.0000,1.0
2020-08-21,123.01,123.4842,122.31,123.16,121.446524411,3385051,0.0000,1.0
2020-08-20,123.2,124.04,122.81,123.15,121.436663537,2561164,0.0000,1.0
2020-08-19,124.83,125.5,123.5,123.84,122.117063844,3743949,0.0000,1.0

In [ ]:
BTC_exchange_rate = Coin_Exchange_Rate()
df = Coin_Exchange_Rate_To_csv(BTC_exchange)